error: XML syntax error on line 3980: unexpected EOF
error: expected element type <definitions> but have <html>
error: expected element type <definitions> but have <html>
error: XML syntax error on line 58: unexpected EOF
error: XML syntax error on line 74: unexpected EOF
error: EOF
error: expected element type <definitions> but have <html>
error: EOF
error: XML syntax error on line 7: unexpected EOF
error: XML syntax error on line 31: unexpected EOF
error: XML syntax error on line 49: unexpected EOF
error: expected element type <definitions> but have <script>
error: XML syntax error on line 17: unexpected EOF

atomService(rdec({var(SearchCustomerRequest,),var(SearchCustomerResponse,)}),sdec(search), sign(openservice,http://sws-challenge.org/moon/services/CRMService), funcR({search},{haha}, {mycloud},in({var(SearchCustomerRequest,)}), out({var(SearchCustomerResponse,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).



atomService(rdec({var(in0,string),var(echoReturn,string)}),sdec(echo), sign(openservice,http://company.com/svc), funcR({echo},{haha}, {mycloud},in({var(in0,string)}), out({var(echoReturn,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(listReturn,ArrayOf_xsd_string)}),sdec(list), sign(openservice,http://company.com/svc), funcR({list},{haha}, {mycloud},in({}), out({var(listReturn,ArrayOf_xsd_string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(whoamiReturn,string)}),sdec(whoami), sign(openservice,http://company.com/svc), funcR({whoami},{haha}, {mycloud},in({}), out({var(whoamiReturn,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(how,int),}),sdec(crash), sign(openservice,http://company.com/svc), funcR({crash},{haha}, {mycloud},in({var(how,int)}), out({})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(FraudLabs), sign(openservice,http://ws.fraudlabs.com/fraudlabswebservice.asmx), funcR({FraudLabs},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(IP,string), var(CITY,string), var(REGION,string), var(POSTAL,string), var(COUNTRY,string), var(DOMAIN,string), var(PHONE,string), var(BIN,string), var(BINNAME,string), var(BINPHONE,string), var(LICENSE,string), var(SHIPADDR,string), var(SHIPCITY,string), var(SHIPREGION,string), var(SHIPPOSTAL,string), var(SHIPCOUNTRY,string), var(QUERYID,string),var(Body,)}),sdec(FraudLabs), sign(openservice,http://ws.fraudlabs.com/fraudlabswebservice.asmx), funcR({FraudLabs},{haha}, {mycloud},in({var(IP,string), var(CITY,string), var(REGION,string), var(POSTAL,string), var(COUNTRY,string), var(DOMAIN,string), var(PHONE,string), var(BIN,string), var(BINNAME,string), var(BINPHONE,string), var(LICENSE,string), var(SHIPADDR,string), var(SHIPCITY,string), var(SHIPREGION,string), var(SHIPPOSTAL,string), var(SHIPCOUNTRY,string), var(QUERYID,string)}), out({var(Body,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(IP,string), var(CITY,string), var(REGION,string), var(POSTAL,string), var(COUNTRY,string), var(DOMAIN,string), var(PHONE,string), var(BIN,string), var(BINNAME,string), var(BINPHONE,string), var(LICENSE,string), var(SHIPADDR,string), var(SHIPCITY,string), var(SHIPREGION,string), var(SHIPPOSTAL,string), var(SHIPCOUNTRY,string), var(QUERYID,string),var(Body,)}),sdec(FraudLabs), sign(openservice,http://ws.fraudlabs.com/fraudlabswebservice.asmx), funcR({FraudLabs},{haha}, {mycloud},in({var(IP,string), var(CITY,string), var(REGION,string), var(POSTAL,string), var(COUNTRY,string), var(DOMAIN,string), var(PHONE,string), var(BIN,string), var(BINNAME,string), var(BINPHONE,string), var(LICENSE,string), var(SHIPADDR,string), var(SHIPCITY,string), var(SHIPREGION,string), var(SHIPPOSTAL,string), var(SHIPCOUNTRY,string), var(QUERYID,string)}), out({var(Body,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(ip,ArrayOfstring), var(username,ArrayOfstring), var(password,ArrayOfstring),var(location,ArrayOfstring)}),sdec(getLocation), sign(openservice,http://www.dns02.de/geolizer/server.php), funcR({getLocation},{haha}, {mycloud},in({var(ip,ArrayOfstring), var(username,ArrayOfstring), var(password,ArrayOfstring)}), out({var(location,ArrayOfstring)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(request,Anfrage1Hersteller),var(response,Antwort1Hersteller)}),sdec(HBObauprodukteDaten1Hersteller), sign(openservice,http://www.heinze.de/index.php), funcR({HBObauprodukteDaten1Hersteller},{haha}, {mycloud},in({var(request,Anfrage1Hersteller)}), out({var(response,Antwort1Hersteller)})), nonFuncR("211.75","59.00","1.10","67.00","0.00",""0", "0")).
atomService(rdec({var(request,AnfragexHersteller),var(response,AntwortxHersteller)}),sdec(HBObauprodukteDatenxHersteller), sign(openservice,http://www.heinze.de/index.php), funcR({HBObauprodukteDatenxHersteller},{haha}, {mycloud},in({var(request,AnfragexHersteller)}), out({var(response,AntwortxHersteller)})), nonFuncR("211.75","59.00","1.10","67.00","0.00",""0", "0")).
atomService(rdec({var(request,Anfrage1Artikel),var(response,Antwort1Artikel)}),sdec(HBObauprodukteDaten1Artikel), sign(openservice,http://www.heinze.de/index.php), funcR({HBObauprodukteDaten1Artikel},{haha}, {mycloud},in({var(request,Anfrage1Artikel)}), out({var(response,Antwort1Artikel)})), nonFuncR("211.75","59.00","1.10","67.00","0.00",""0", "0")).
atomService(rdec({var(request,AnfragexArtikel),var(response,AntwortxArtikel)}),sdec(HBObauprodukteDatenxArtikel), sign(openservice,http://www.heinze.de/index.php), funcR({HBObauprodukteDatenxArtikel},{haha}, {mycloud},in({var(request,AnfragexArtikel)}), out({var(response,AntwortxArtikel)})), nonFuncR("211.75","59.00","1.10","67.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsLicenseCode,string), var(bsLicenseType,string), var(bsExpired,string), var(bsCheckSubscription,string),var(CheckSubscriptionResult,int), var(bsExpired,string), var(bsCheckSubscription,string)}),sdec(CheckSubscription), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({CheckSubscription},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsLicenseCode,string), var(bsLicenseType,string), var(bsExpired,string), var(bsCheckSubscription,string)}), out({var(CheckSubscriptionResult,int), var(bsExpired,string), var(bsCheckSubscription,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsAdsAsXML,string),var(DownloadBannerAdsResult,int), var(pbsAdsAsXML,string)}),sdec(DownloadBannerAds), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({DownloadBannerAds},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsAdsAsXML,string)}), out({var(DownloadBannerAdsResult,int), var(pbsAdsAsXML,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(nBannerAdID,long), var(pbsURL,string),var(GetBannerAdURLResult,int), var(pbsURL,string)}),sdec(GetBannerAdURL), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetBannerAdURL},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(nBannerAdID,long), var(pbsURL,string)}), out({var(GetBannerAdURLResult,int), var(pbsURL,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(nStatus,long), var(pbsURL,string),var(GetInTouchURLResult,int), var(pbsURL,string)}),sdec(GetInTouchURL), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetInTouchURL},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(nStatus,long), var(pbsURL,string)}), out({var(GetInTouchURLResult,int), var(pbsURL,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(nStatus,long), var(nSource,long), var(pbsURL,string),var(GetInTouchURLExResult,int), var(pbsURL,string)}),sdec(GetInTouchURLEx), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetInTouchURLEx},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(nStatus,long), var(nSource,long), var(pbsURL,string)}), out({var(GetInTouchURLExResult,int), var(pbsURL,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsSignupXML,string),var(NewsletterSignupResult,int)}),sdec(NewsletterSignup), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({NewsletterSignup},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsSignupXML,string)}), out({var(NewsletterSignupResult,int)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(nProductID,long), var(nPackageFlags,long), var(bsLanguage,string), var(bsTrialUnlockXML,string),var(RequestTrialCodeResult,int)}),sdec(RequestTrialCode), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({RequestTrialCode},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(nProductID,long), var(nPackageFlags,long), var(bsLanguage,string), var(bsTrialUnlockXML,string)}), out({var(RequestTrialCodeResult,int)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsLicenseCode,string),var(VerifyTrialUnlockResult,int), var(pbsLicenseCode,string)}),sdec(VerifyTrialUnlock), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({VerifyTrialUnlock},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsLicenseCode,string)}), out({var(VerifyTrialUnlockResult,int), var(pbsLicenseCode,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsMachineID,string), var(bsLicenseCode,string), var(nSeats,long), var(pbsActivationCode,string),var(ActivateProductResult,int), var(pbsActivationCode,string)}),sdec(ActivateProduct), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({ActivateProduct},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsMachineID,string), var(bsLicenseCode,string), var(nSeats,long), var(pbsActivationCode,string)}), out({var(ActivateProductResult,int), var(pbsActivationCode,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsProductListXML,string),var(GetProductListResult,int), var(pbsProductListXML,string)}),sdec(GetProductList), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetProductList},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsProductListXML,string)}), out({var(GetProductListResult,int), var(pbsProductListXML,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsServiceListXML,string),var(GetServicesListResult,int), var(pbsServiceListXML,string)}),sdec(GetServicesList), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetServicesList},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsServiceListXML,string)}), out({var(GetServicesListResult,int), var(pbsServiceListXML,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsResultAsXML,string),var(GetStaticPagesResult,int), var(pbsResultAsXML,string)}),sdec(GetStaticPages), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetStaticPages},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsResultAsXML,string)}), out({var(GetStaticPagesResult,int), var(pbsResultAsXML,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string),var(IsAliveResult,boolean)}),sdec(IsAlive), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({IsAlive},{haha}, {mycloud},in({var(bsAuthentication,string)}), out({var(IsAliveResult,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsProductInfoTreeAsXML,string),var(UploadProductInfoTreeResult,int)}),sdec(UploadProductInfoTree), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({UploadProductInfoTree},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsProductInfoTreeAsXML,string)}), out({var(UploadProductInfoTreeResult,int)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsProductInfoTreeAsXML,string), var(pnFlags,long),var(UploadProductInfoTreeExResult,int), var(pnFlags,long)}),sdec(UploadProductInfoTreeEx), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({UploadProductInfoTreeEx},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsProductInfoTreeAsXML,string), var(pnFlags,long)}), out({var(UploadProductInfoTreeExResult,int), var(pnFlags,long)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsUserProfileID,string), var(nProductID,long), var(nCompanyID,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(bsActivationNum,string), var(bsInstallDate,string), var(bsTrialStartDate,string), var(nTrialMode,long), var(bsOSVersion,string), var(nUsageCount,long), var(pbsNewUserProfileID,anyType), var(pbGetStaticPages,anyType), var(pbGetBannerAds,anyType),var(UploadProfileResult,int), var(pbsNewUserProfileID,anyType), var(pbGetStaticPages,anyType), var(pbGetBannerAds,anyType)}),sdec(UploadProfile), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({UploadProfile},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsUserProfileID,string), var(nProductID,long), var(nCompanyID,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(bsActivationNum,string), var(bsInstallDate,string), var(bsTrialStartDate,string), var(nTrialMode,long), var(bsOSVersion,string), var(nUsageCount,long), var(pbsNewUserProfileID,anyType), var(pbGetStaticPages,anyType), var(pbGetBannerAds,anyType)}), out({var(UploadProfileResult,int), var(pbsNewUserProfileID,anyType), var(pbGetStaticPages,anyType), var(pbGetBannerAds,anyType)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsUserProfileID,string), var(nProductID,long), var(nCompanyID,long), var(nParentProductID,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(bsActivationNum,string), var(bsInstallDate,string), var(bsTrialStartDate,string), var(nTrialMode,long), var(bsOSVersion,string), var(nUsageCount,long), var(pbsNewUserProfileID,string), var(pnFlags,long), var(nStatus,long),var(UploadProfileExResult,int), var(pbsNewUserProfileID,string), var(pnFlags,long)}),sdec(UploadProfileEx), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({UploadProfileEx},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsUserProfileID,string), var(nProductID,long), var(nCompanyID,long), var(nParentProductID,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(bsActivationNum,string), var(bsInstallDate,string), var(bsTrialStartDate,string), var(nTrialMode,long), var(bsOSVersion,string), var(nUsageCount,long), var(pbsNewUserProfileID,string), var(pnFlags,long), var(nStatus,long)}), out({var(UploadProfileExResult,int), var(pbsNewUserProfileID,string), var(pnFlags,long)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsUserProfileID,string), var(nProductID,long), var(nParentProductID,long), var(nFullPackageFlags,long), var(nTrialPackageFlags,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(bsActivationNum,string), var(bsInstallDate,string), var(bsTrialStartDate,string), var(nTrialMode,long), var(bsOSVersion,string), var(nUsageCount,long), var(bsProductTag,string), var(bsCampaignID,string), var(pnFlags,long), var(nStatus,long),var(UploadProfileEx2Result,int), var(pnFlags,long)}),sdec(UploadProfileEx2), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({UploadProfileEx2},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsUserProfileID,string), var(nProductID,long), var(nParentProductID,long), var(nFullPackageFlags,long), var(nTrialPackageFlags,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(bsActivationNum,string), var(bsInstallDate,string), var(bsTrialStartDate,string), var(nTrialMode,long), var(bsOSVersion,string), var(nUsageCount,long), var(bsProductTag,string), var(bsCampaignID,string), var(pnFlags,long), var(nStatus,long)}), out({var(UploadProfileEx2Result,int), var(pnFlags,long)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsStatsAsXML,string),var(UploadStatsResult,int)}),sdec(UploadStats), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({UploadStats},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(bsStatsAsXML,string)}), out({var(UploadStatsResult,int)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsXMLIn,string), var(pbsXMLOut,string),var(XMLQueryResult,int), var(pbsXMLOut,string)}),sdec(XMLQuery), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({XMLQuery},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsXMLIn,string), var(pbsXMLOut,string)}), out({var(XMLQueryResult,int), var(pbsXMLOut,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(GetVersionResult,string)}),sdec(GetVersion), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetVersion},{haha}, {mycloud},in({}), out({var(GetVersionResult,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsURL,string),var(GetInTouchFileURLResult,int), var(pbsURL,string)}),sdec(GetInTouchFileURL), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetInTouchFileURL},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(pbsURL,string)}), out({var(GetInTouchFileURLResult,int), var(pbsURL,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(nProductID,long), var(nPackageFlags,long), var(bsLanguage,string), var(nTrialLength,long), var(pbsLicenseCode,string),var(GetTrialLicenseCodeResult,int), var(pbsLicenseCode,string)}),sdec(GetTrialLicenseCode), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetTrialLicenseCode},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(nProductID,long), var(nPackageFlags,long), var(bsLanguage,string), var(nTrialLength,long), var(pbsLicenseCode,string)}), out({var(GetTrialLicenseCodeResult,int), var(pbsLicenseCode,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(bsAuthentication,string), var(bsAppProfileID,string), var(nProductID,long), var(nParentProductID,long), var(nFullPackageFlags,long), var(nTrialPackageFlags,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(nTrialMode,long), var(nDayOfTrial,long), var(bsProductTag,string), var(bsCampaignID,string), var(pbsOfferURL,string),var(GetOfferURLResult,int), var(pbsOfferURL,string)}),sdec(GetOfferURL), sign(openservice,http://soapintouch.acdnet.com/InTouchService.asmx), funcR({GetOfferURL},{haha}, {mycloud},in({var(bsAuthentication,string), var(bsAppProfileID,string), var(nProductID,long), var(nParentProductID,long), var(nFullPackageFlags,long), var(nTrialPackageFlags,long), var(bsProductVersion,string), var(bsProductMode,string), var(bsLanguage,string), var(nTrialMode,long), var(nDayOfTrial,long), var(bsProductTag,string), var(bsCampaignID,string), var(pbsOfferURL,string)}), out({var(GetOfferURLResult,int), var(pbsOfferURL,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(myInput,inputAgenda),var(return,outputAgenda)}),sdec(KpiLastReport), sign(openservice,http://www.chiangmaipoc.net/webservice/kpireport.php), funcR({KpiLastReport},{haha}, {mycloud},in({var(myInput,inputAgenda)}), out({var(return,outputAgenda)})), nonFuncR("1275.25","56.00","3.00","67.00","0.00",""0", "0")).
atomService(rdec({var(myInput,inputRDP),var(return,outputRDP)}),sdec(result_dimension_parent), sign(openservice,http://www.chiangmaipoc.net/webservice/kpireport.php), funcR({result_dimension_parent},{haha}, {mycloud},in({var(myInput,inputRDP)}), out({var(return,outputRDP)})), nonFuncR("1275.25","56.00","3.00","67.00","0.00",""0", "0")).
atomService(rdec({var(myInput,inputRD),var(return,outputRD)}),sdec(result_dimension), sign(openservice,http://www.chiangmaipoc.net/webservice/kpireport.php), funcR({result_dimension},{haha}, {mycloud},in({var(myInput,inputRD)}), out({var(return,outputRD)})), nonFuncR("1275.25","56.00","3.00","67.00","0.00",""0", "0")).
atomService(rdec({var(myInput,inputAll),var(return,outputAll)}),sdec(KpiAll), sign(openservice,http://www.chiangmaipoc.net/webservice/kpireport.php), funcR({KpiAll},{haha}, {mycloud},in({var(myInput,inputAll)}), out({var(return,outputAll)})), nonFuncR("1275.25","56.00","3.00","67.00","0.00",""0", "0")).

atomService(rdec({var(inmessage,string),var(return,helloWorldReturn)}),sdec(helloWorld), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({helloWorld},{haha}, {mycloud},in({var(inmessage,string)}), out({var(return,helloWorldReturn)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(SayThis,string), var(NTimes,int),var(return,ArrayOfStrings)}),sdec(SayThisNTimes), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({SayThisNTimes},{haha}, {mycloud},in({var(SayThis,string), var(NTimes,int)}), out({var(return,ArrayOfStrings)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(inmessage,string),var(outmessage,string)}),sdec(helloWorldSimple), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({helloWorldSimple},{haha}, {mycloud},in({var(inmessage,string)}), out({var(outmessage,string)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(namebankID,int), var(keyCode,string),var(namebankObject,namebankObject)}),sdec(namebank_object), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_object},{haha}, {mycloud},in({var(namebankID,int), var(keyCode,string)}), out({var(namebankObject,namebankObject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(searchName,string), var(searchAuth,string), var(searchYear,string), var(order,string), var(rank,string), var(sci,int), var(linkedVern,int), var(vern,int), var(keyCode,string),var(matching_names,AllNames)}),sdec(namebank_search), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_search},{haha}, {mycloud},in({var(searchName,string), var(searchAuth,string), var(searchYear,string), var(order,string), var(rank,string), var(sci,int), var(linkedVern,int), var(vern,int), var(keyCode,string)}), out({var(matching_names,AllNames)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(searchName,string), var(searchAuth,string), var(searchYear,string), var(order,string), var(rank,string), var(sci,int), var(linkedVern,int), var(vern,int), var(keyCode,string),var(matching_names,AllNames)}),sdec(namebank_search2), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_search2},{haha}, {mycloud},in({var(searchName,string), var(searchAuth,string), var(searchYear,string), var(order,string), var(rank,string), var(sci,int), var(linkedVern,int), var(vern,int), var(keyCode,string)}), out({var(matching_names,AllNames)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(searchName,string), var(searchAuth,string), var(searchYear,string), var(order,string), var(rank,string), var(sci,int), var(linkedVern,int), var(vern,int), var(keyCode,string),var(matching_names,StructuredAllNames)}),sdec(namebank_search_structured), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_search_structured},{haha}, {mycloud},in({var(searchName,string), var(searchAuth,string), var(searchYear,string), var(order,string), var(rank,string), var(sci,int), var(linkedVern,int), var(vern,int), var(keyCode,string)}), out({var(matching_names,StructuredAllNames)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(searchAuth,string), var(searchQualifier,string), var(limitBP,int), var(returnXML,int),var(matching_authors,AllAuthors)}),sdec(namebank_search_authors), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_search_authors},{haha}, {mycloud},in({var(searchAuth,string), var(searchQualifier,string), var(limitBP,int), var(returnXML,int)}), out({var(matching_authors,AllAuthors)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(groupID,int), var(returnXML,int),var(author_group,AuthorObject)}),sdec(namebank_object_authors), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_object_authors},{haha}, {mycloud},in({var(groupID,int), var(returnXML,int)}), out({var(author_group,AuthorObject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(url,string), var(freeText,string), var(strict,int), var(threshold,float),var(findITobject,findITobject)}),sdec(findIT), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({findIT},{haha}, {mycloud},in({var(url,string), var(freeText,string), var(strict,int), var(threshold,float)}), out({var(findITobject,findITobject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(url,string), var(freeText,string), var(includeLinks,int),var(findITobject,findITobject)}),sdec(taxonFinder), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({taxonFinder},{haha}, {mycloud},in({var(url,string), var(freeText,string), var(includeLinks,int)}), out({var(findITobject,findITobject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(document,string), var(strict,int), var(threshold,float),var(findITobject,findITobject)}),sdec(findIT_landcare), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({findIT_landcare},{haha}, {mycloud},in({var(document,string), var(strict,int), var(threshold,float)}), out({var(findITobject,findITobject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(document,string),var(findITobject,findITobject)}),sdec(reconcile), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({reconcile},{haha}, {mycloud},in({var(document,string)}), out({var(findITobject,findITobject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(namebankID,int), var(clientVersion,string), var(requestorIP,string), var(classificationTitleID,int), var(keyCode,string),var(AllHierarchies,AllHierarchies)}),sdec(classificationbank_search), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({classificationbank_search},{haha}, {mycloud},in({var(namebankID,int), var(clientVersion,string), var(requestorIP,string), var(classificationTitleID,int), var(keyCode,string)}), out({var(AllHierarchies,AllHierarchies)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(hierarchiesID,int), var(childrenFlag,int), var(ancestryFlag,int), var(justificationsFlag,int), var(synonymsFlag,int), var(clientVersion,string), var(requestorIP,string), var(keyCode,string),var(classificationBankObject,classificationBankObject)}),sdec(classificationbank_object), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({classificationbank_object},{haha}, {mycloud},in({var(hierarchiesID,int), var(childrenFlag,int), var(ancestryFlag,int), var(justificationsFlag,int), var(synonymsFlag,int), var(clientVersion,string), var(requestorIP,string), var(keyCode,string)}), out({var(classificationBankObject,classificationBankObject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(packageID,int), var(clientVersion,string), var(requestorIP,string), var(keyCode,string),var(packageList,packageList)}),sdec(namebank_packageList), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({namebank_packageList},{haha}, {mycloud},in({var(packageID,int), var(clientVersion,string), var(requestorIP,string), var(keyCode,string)}), out({var(packageList,packageList)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(classificationTitleID,int), var(clientVersion,string), var(requestorIP,string), var(keyCode,string),var(classificationList,classificationList)}),sdec(classification_list), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({classification_list},{haha}, {mycloud},in({var(classificationTitleID,int), var(clientVersion,string), var(requestorIP,string), var(keyCode,string)}), out({var(classificationList,classificationList)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(clientVersion,string), var(requestorIP,string), var(keyCode,string),var(languageList,StringArray)}),sdec(language_list), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({language_list},{haha}, {mycloud},in({var(clientVersion,string), var(requestorIP,string), var(keyCode,string)}), out({var(languageList,StringArray)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(hierarchiesID,intarray), var(clientVersion,string), var(requestorIP,string), var(keyCode,string),var(classificationBankObject,classificationBankObject)}),sdec(synonym_list), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({synonym_list},{haha}, {mycloud},in({var(hierarchiesID,intarray), var(clientVersion,string), var(requestorIP,string), var(keyCode,string)}), out({var(classificationBankObject,classificationBankObject)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(nameString,string),var(people,splitArray)}),sdec(split_name), sign(openservice,http://names.mbl.edu/soap/index.php), funcR({split_name},{haha}, {mycloud},in({var(nameString,string)}), out({var(people,splitArray)})), nonFuncR("310.25","22.00","2.80","42.00","0.00",""0", "0")).
atomService(rdec({var(plant,string), var(id,string), var(start,string), var(end,string), var(gps,ArrayOfstring), var(owners,ArrayOfint), var(categories,ArrayOfint), var(planning,ArrayOfint), var(assessment,ArrayOfint), var(last_modified,string),var(return,ArrayOfOutage)}),sdec(search), sign(openservice,http://pocp.redspider.co.nz/soap.php), funcR({search},{haha}, {mycloud},in({var(plant,string), var(id,string), var(start,string), var(end,string), var(gps,ArrayOfstring), var(owners,ArrayOfint), var(categories,ArrayOfint), var(planning,ArrayOfint), var(assessment,ArrayOfint), var(last_modified,string)}), out({var(return,ArrayOfOutage)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfMapping)}),sdec(owner_list), sign(openservice,http://pocp.redspider.co.nz/soap.php), funcR({owner_list},{haha}, {mycloud},in({}), out({var(return,ArrayOfMapping)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfMapping)}),sdec(category_list), sign(openservice,http://pocp.redspider.co.nz/soap.php), funcR({category_list},{haha}, {mycloud},in({}), out({var(return,ArrayOfMapping)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfMapping)}),sdec(assessment_status_list), sign(openservice,http://pocp.redspider.co.nz/soap.php), funcR({assessment_status_list},{haha}, {mycloud},in({}), out({var(return,ArrayOfMapping)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfMapping)}),sdec(planning_status_list), sign(openservice,http://pocp.redspider.co.nz/soap.php), funcR({planning_status_list},{haha}, {mycloud},in({}), out({var(return,ArrayOfMapping)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).

atomService(rdec({var(Pip3A4PurchaseOrderConfirmation,),var(ACK,)}),sdec(receiveConfirmation), sign(openservice,http://sws-challenge.org/moon/services/RNetService), funcR({receiveConfirmation},{haha}, {mycloud},in({var(Pip3A4PurchaseOrderConfirmation,)}), out({var(ACK,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).

atomService(rdec({var(RangoFechaInicio,string), var(RangoFechaFin,string),var(return,DatasetRespuesta)}),sdec(ReporteAereo), sign(openservice,http://www.inbolpack.net/transredes2/WSRepAereo.php), funcR({ReporteAereo},{haha}, {mycloud},in({var(RangoFechaInicio,string), var(RangoFechaFin,string)}), out({var(return,DatasetRespuesta)})), nonFuncR("235.00","83.00","23.50","67.00","0.00",""0", "0")).
atomService(rdec({var(data,AreaFetch),var(return,AreaList)}),sdec(area_list), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({area_list},{haha}, {mycloud},in({var(data,AreaFetch)}), out({var(return,AreaList)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(inputStructArray,AreaFetch),var(return,AreaRes)}),sdec(area_getinfo), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({area_getinfo},{haha}, {mycloud},in({var(inputStructArray,AreaFetch)}), out({var(return,AreaRes)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,EventListFetch),var(return,EventList)}),sdec(event_list), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({event_list},{haha}, {mycloud},in({var(data,EventListFetch)}), out({var(return,EventList)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,EventFetch),var(return,EventRes)}),sdec(event_getinfo), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({event_getinfo},{haha}, {mycloud},in({var(data,EventFetch)}), out({var(return,EventRes)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,EventFetch),var(return,EventRes)}),sdec(event_show), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({event_show},{haha}, {mycloud},in({var(data,EventFetch)}), out({var(return,EventRes)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,EventAdd),var(return,EventAddRes)}),sdec(event_add), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({event_add},{haha}, {mycloud},in({var(data,EventAdd)}), out({var(return,EventAddRes)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,EventAdd),var(return,EventFetch)}),sdec(event_update), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({event_update},{haha}, {mycloud},in({var(data,EventAdd)}), out({var(return,EventFetch)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,UserFetch),var(return,UserRes)}),sdec(user_getinfo), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({user_getinfo},{haha}, {mycloud},in({var(data,UserFetch)}), out({var(return,UserRes)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(data,UserFetch),var(return,AreaRes)}),sdec(user_getarea), sign(openservice,http://www.spraci.com/services/soap/index.php), funcR({user_getarea},{haha}, {mycloud},in({var(data,UserFetch)}), out({var(return,AreaRes)})), nonFuncR("667.11","38.00","2.10","73.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(login), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({login},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(describeSObject), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({describeSObject},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(describeSObjects), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({describeSObjects},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(describeGlobal), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({describeGlobal},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(describeLayout), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({describeLayout},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(describeSoftphoneLayout), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({describeSoftphoneLayout},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(describeTabs), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({describeTabs},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(create), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({create},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(update), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({update},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(upsert), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({upsert},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(merge), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({merge},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(delete), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({delete},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(undelete), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({undelete},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(retrieve), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({retrieve},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(process), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({process},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(convertLead), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({convertLead},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(getDeleted), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({getDeleted},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(getUpdated), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({getUpdated},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(query), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({query},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(queryAll), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({queryAll},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(queryMore), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({queryMore},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(search), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({search},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(getServerTimestamp), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({getServerTimestamp},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(setPassword), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({setPassword},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(resetPassword), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({resetPassword},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(getUserInfo), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({getUserInfo},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(sendEmail), sign(openservice,http://www.salesforce.com/services/Soap/u/9.0), funcR({sendEmail},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStocksXMLSchema), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStocksXMLSchema},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStockDailyValuesByValueXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStockDailyValuesByValueXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStockDailyValuesByDateXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStockDailyValuesByDateXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStockDailyValuesXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStockDailyValuesXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestStockDailyValuesXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestStockDailyValuesXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStockDailyValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStockDailyValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetPreviousStockDailyValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetPreviousStockDailyValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestStockDailyValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestStockDailyValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestPreviousStockDailyValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestPreviousStockDailyValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestStockValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestStockValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStockValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStockValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetStockValuesByDateTimeXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetStockValuesByDateTimeXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndicesXMLSchema), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndicesXMLSchema},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndexDailyValuesByValueXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndexDailyValuesByValueXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndexDailyValuesByDateXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndexDailyValuesByDateXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndexDailyValuesXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndexDailyValuesXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestIndexDailyValuesXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestIndexDailyValuesXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndexDailyValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndexDailyValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestIndexDailyValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestIndexDailyValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetLatestIndexValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetLatestIndexValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndexValue), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndexValue},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(GetIndexValuesByDateTimeXML), sign(openservice,http://webservices.gama-system.com/stockquotes.asmx), funcR({GetIndexValuesByDateTimeXML},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(listName,string),var(return,listType)}),sdec(info), sign(openservice,http://demo.sympa.org/soap), funcR({info},{haha}, {mycloud},in({var(listName,string)}), out({var(return,listType)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfLists)}),sdec(complexWhich), sign(openservice,http://demo.sympa.org/soap), funcR({complexWhich},{haha}, {mycloud},in({}), out({var(return,ArrayOfLists)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfString)}),sdec(which), sign(openservice,http://demo.sympa.org/soap), funcR({which},{haha}, {mycloud},in({}), out({var(return,ArrayOfString)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string), var(function,string), var(user,string),var(return,boolean)}),sdec(amI), sign(openservice,http://demo.sympa.org/soap), funcR({amI},{haha}, {mycloud},in({var(list,string), var(function,string), var(user,string)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string), var(email,string), var(gecos,string), var(quiet,boolean),var(return,boolean)}),sdec(add), sign(openservice,http://demo.sympa.org/soap), funcR({add},{haha}, {mycloud},in({var(list,string), var(email,string), var(gecos,string), var(quiet,boolean)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string), var(email,string), var(quiet,boolean),var(return,boolean)}),sdec(del), sign(openservice,http://demo.sympa.org/soap), funcR({del},{haha}, {mycloud},in({var(list,string), var(email,string), var(quiet,boolean)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string), var(subject,string), var(template,string), var(description,string), var(topics,string),var(return,boolean)}),sdec(createList), sign(openservice,http://demo.sympa.org/soap), funcR({createList},{haha}, {mycloud},in({var(list,string), var(subject,string), var(template,string), var(description,string), var(topics,string)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string),var(return,boolean)}),sdec(closeList), sign(openservice,http://demo.sympa.org/soap), funcR({closeList},{haha}, {mycloud},in({var(list,string)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string),var(return,ArrayOfString)}),sdec(review), sign(openservice,http://demo.sympa.org/soap), funcR({review},{haha}, {mycloud},in({var(list,string)}), out({var(return,ArrayOfString)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string),var(return,ArrayOfUsers)}),sdec(fullReview), sign(openservice,http://demo.sympa.org/soap), funcR({fullReview},{haha}, {mycloud},in({var(list,string)}), out({var(return,ArrayOfUsers)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string), var(gecos,string),var(return,boolean)}),sdec(subscribe), sign(openservice,http://demo.sympa.org/soap), funcR({subscribe},{haha}, {mycloud},in({var(list,string), var(gecos,string)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(list,string), var(email,string),var(return,boolean)}),sdec(signoff), sign(openservice,http://demo.sympa.org/soap), funcR({signoff},{haha}, {mycloud},in({var(list,string), var(email,string)}), out({var(return,boolean)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(email,string), var(password,string),var(return,string)}),sdec(login), sign(openservice,http://demo.sympa.org/soap), funcR({login},{haha}, {mycloud},in({var(email,string), var(password,string)}), out({var(return,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(proxyTicket,string),var(return,string)}),sdec(casLogin), sign(openservice,http://demo.sympa.org/soap), funcR({casLogin},{haha}, {mycloud},in({var(proxyTicket,string)}), out({var(return,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(cookie,string),var(return,string)}),sdec(getUserEmailByCookie), sign(openservice,http://demo.sympa.org/soap), funcR({getUserEmailByCookie},{haha}, {mycloud},in({var(cookie,string)}), out({var(return,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(email,string), var(cookie,string), var(service,string), var(parameters,ArrayOfString),var(return,ArrayOfString)}),sdec(authenticateAndRun), sign(openservice,http://demo.sympa.org/soap), funcR({authenticateAndRun},{haha}, {mycloud},in({var(email,string), var(cookie,string), var(service,string), var(parameters,ArrayOfString)}), out({var(return,ArrayOfString)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(appname,string), var(apppassword,string), var(vars,string), var(service,string), var(parameters,ArrayOfString),var(return,ArrayOfString)}),sdec(authenticateRemoteAppAndRun), sign(openservice,http://demo.sympa.org/soap), funcR({authenticateRemoteAppAndRun},{haha}, {mycloud},in({var(appname,string), var(apppassword,string), var(vars,string), var(service,string), var(parameters,ArrayOfString)}), out({var(return,ArrayOfString)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(topic,string), var(subtopic,string),var(listInfo,string)}),sdec(lists), sign(openservice,http://demo.sympa.org/soap), funcR({lists},{haha}, {mycloud},in({var(topic,string), var(subtopic,string)}), out({var(listInfo,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(return,ArrayOfLists)}),sdec(complexLists), sign(openservice,http://demo.sympa.org/soap), funcR({complexLists},{haha}, {mycloud},in({}), out({var(return,ArrayOfLists)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({,var(email,string)}),sdec(checkCookie), sign(openservice,http://demo.sympa.org/soap), funcR({checkCookie},{haha}, {mycloud},in({}), out({var(email,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).

atomService(rdec({var(format,string), var(ids,string),var(result,string)}),sdec(getNucSeq), sign(openservice,http://www.ebi.ac.uk:80/cgi-bin/xembl/XEMBL-SOAP.pl), funcR({getNucSeq},{haha}, {mycloud},in({var(format,string), var(ids,string)}), out({var(result,string)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(filename,string),var(return,base64Binary)}),sdec(getFile), sign(openservice,http://www.scottnichol.com/samples/getfile2.php), funcR({getFile},{haha}, {mycloud},in({var(filename,string)}), out({var(return,base64Binary)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).

atomService(rdec({var(person,Person),var(return,SweepstakesGreeting)}),sdec(hello), sign(openservice,http://www.scottnichol.com/samples/hellowsdl2.php), funcR({hello},{haha}, {mycloud},in({var(person,Person)}), out({var(return,SweepstakesGreeting)})), nonFuncR("223.67","63.00","5.10","73.00","0.00",""0", "0")).
atomService(rdec({var(person,Person),var(return,SweepstakesGreeting)}),sdec(hellowsdl2.hello), sign(openservice,http://www.scottnichol.com/samples/hellowsdl2.php), funcR({hellowsdl2.hello},{haha}, {mycloud},in({var(person,Person)}), out({var(return,SweepstakesGreeting)})), nonFuncR("223.67","63.00","5.10","73.00","0.00",""0", "0")).
atomService(rdec({var(person,Person),var(return,SweepstakesGreeting)}),sdec(hellowsdl2..hello), sign(openservice,http://www.scottnichol.com/samples/hellowsdl2.php), funcR({hellowsdl2..hello},{haha}, {mycloud},in({var(person,Person)}), out({var(return,SweepstakesGreeting)})), nonFuncR("223.67","63.00","5.10","73.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(mt), sign(openservice,http://www.translated.net/hts/soap.php), funcR({mt},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(quote), sign(openservice,http://www.translated.net/hts/soap.php), funcR({quote},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(confirm), sign(openservice,http://www.translated.net/hts/soap.php), funcR({confirm},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(cc), sign(openservice,http://www.translated.net/hts/soap.php), funcR({cc},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(ll), sign(openservice,http://www.translated.net/hts/soap.php), funcR({ll},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(lc), sign(openservice,http://www.translated.net/hts/soap.php), funcR({lc},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).
atomService(rdec({var(parameters,),var(parameters,)}),sdec(status), sign(openservice,http://www.translated.net/hts/soap.php), funcR({status},{haha}, {mycloud},in({var(parameters,)}), out({var(parameters,)})), nonFuncR("0.00","0.00","0.00","0.00","0.00",""0", "0")).


atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(status,string)}),sdec(doCounterDelete), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doCounterDelete},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(status,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(e-mail,string), var(name,string), var(surname,string),var(result,string)}),sdec(doDataStorage), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doDataStorage},{haha}, {mycloud},in({var(webapi-key,string), var(e-mail,string), var(name,string), var(surname,string)}), out({var(result,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(expiration-date,string), var(modification-datetime,string)}),sdec(doDealerInsertionActivate), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doDealerInsertionActivate},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(expiration-date,string), var(modification-datetime,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(status,string), var(remove-date,string), var(modification-datetime,string)}),sdec(doDealerInsertionInactivate), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doDealerInsertionInactivate},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(status,string), var(remove-date,string), var(modification-datetime,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(dealer-login,string), var(dealer-password,string), var(country-code,string), var(webapi-key,string),var(session-id,string), var(dealer,Dealer)}),sdec(doDealerLogin), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doDealerLogin},{haha}, {mycloud},in({var(dealer-login,string), var(dealer-password,string), var(country-code,string), var(webapi-key,string)}), out({var(session-id,string), var(dealer,Dealer)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(session-id,string), var(webapi-key,string),var(result,string)}),sdec(doDealerLogout), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doDealerLogout},{haha}, {mycloud},in({var(session-id,string), var(webapi-key,string)}), out({var(result,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(limit,int), var(page,int), var(name,string), var(country-id,string), var(province-id,int), var(city,string),var(results-list,ArrayOfDealers), var(results-count,string)}),sdec(doDealerSearch), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doDealerSearch},{haha}, {mycloud},in({var(webapi-key,string), var(limit,int), var(page,int), var(name,string), var(country-id,string), var(province-id,int), var(city,string)}), out({var(results-list,ArrayOfDealers), var(results-count,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(partner-id,string), var(partner-password,string), var(order-type,string), var(webapi-key,string),var(insertions-list,ArrayOfExportInfos)}),sdec(doExport), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doExport},{haha}, {mycloud},in({var(partner-id,string), var(partner-password,string), var(order-type,string), var(webapi-key,string)}), out({var(insertions-list,ArrayOfExportInfos)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(partner-id,string), var(partner-password,string), var(export-info-list,ArrayOfExportInfos), var(webapi-key,string),var(status,string)}),sdec(doExportAck), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doExportAck},{haha}, {mycloud},in({var(partner-id,string), var(partner-password,string), var(export-info-list,ArrayOfExportInfos), var(webapi-key,string)}), out({var(status,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(test-hello-string,string),var(return-string,string)}),sdec(doHello), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doHello},{haha}, {mycloud},in({var(test-hello-string,string)}), out({var(return-string,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(status,string)}),sdec(doInsertionDelete), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionDelete},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(status,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(status,string), var(error-list,ArrayOfFormErrors), var(insertion,Insertion)}),sdec(doInsertionEdit), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionEdit},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(status,string), var(error-list,ArrayOfFormErrors), var(insertion,Insertion)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(user-email,string), var(password,string), var(webapi-key,string),var(session-id,string), var(insertion,Insertion)}),sdec(doInsertionLogin), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionLogin},{haha}, {mycloud},in({var(user-email,string), var(password,string), var(webapi-key,string)}), out({var(session-id,string), var(insertion,Insertion)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(session-id,string), var(webapi-key,string),var(result,string)}),sdec(doInsertionLogout), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionLogout},{haha}, {mycloud},in({var(session-id,string), var(webapi-key,string)}), out({var(result,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(make-model-phrase,string), var(make-id,int), var(model-name,string), var(price-from,int), var(price-to,int), var(price-currency,string), var(build-year-from,int), var(build-year-to,int), var(odometer-from,int), var(odometer-to,int), var(fuel-type-key,string), var(country-id,string), var(province-id,int), var(city-name,string), var(vehicle-category-key,string), var(order-by,string), var(webapi-key,string), var(only-promoted,string), var(model-id,int), var(dealer-id,int), var(part-kind-vehicle,string), var(part-category-id,int), var(sort,string), var(extras-list,ArrayOfVehicleExtras), var(features-list,ArrayOfVehicleFeatures), var(cubic-capacity-from,int), var(cubic-capacity-to,int), var(gearbox,string), var(doors,string), var(colour,string), var(metallic,string), var(origin-country,string), var(registration-country,string),var(search-query-id,long), var(status,string), var(results-no,int), var(error-list,ArrayOfFormErrors)}),sdec(doInsertionSearch), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionSearch},{haha}, {mycloud},in({var(type,string), var(make-model-phrase,string), var(make-id,int), var(model-name,string), var(price-from,int), var(price-to,int), var(price-currency,string), var(build-year-from,int), var(build-year-to,int), var(odometer-from,int), var(odometer-to,int), var(fuel-type-key,string), var(country-id,string), var(province-id,int), var(city-name,string), var(vehicle-category-key,string), var(order-by,string), var(webapi-key,string), var(only-promoted,string), var(model-id,int), var(dealer-id,int), var(part-kind-vehicle,string), var(part-category-id,int), var(sort,string), var(extras-list,ArrayOfVehicleExtras), var(features-list,ArrayOfVehicleFeatures), var(cubic-capacity-from,int), var(cubic-capacity-to,int), var(gearbox,string), var(doors,string), var(colour,string), var(metallic,string), var(origin-country,string), var(registration-country,string)}), out({var(search-query-id,long), var(status,string), var(results-no,int), var(error-list,ArrayOfFormErrors)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(partner-id,string), var(partner-password,string), var(webapi-key,string),var(status,string), var(list,ArrayOfTransferUnits)}),sdec(doInsertionTransfer), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionTransfer},{haha}, {mycloud},in({var(partner-id,string), var(partner-password,string), var(webapi-key,string)}), out({var(status,string), var(list,ArrayOfTransferUnits)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(partner-id,string), var(partner-password,string), var(transfer-unit-list,ArrayOfTransferUnits), var(webapi-key,string),var(status,string)}),sdec(doInsertionTransferAck), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doInsertionTransferAck},{haha}, {mycloud},in({var(partner-id,string), var(partner-password,string), var(transfer-unit-list,ArrayOfTransferUnits), var(webapi-key,string)}), out({var(status,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(expiration-date,string), var(modification-datetime,string)}),sdec(doPartnerInsertionActivate), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPartnerInsertionActivate},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(expiration-date,string), var(modification-datetime,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(status,string), var(remove-date,string), var(modification-datetime,string)}),sdec(doPartnerInsertionInactivate), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPartnerInsertionInactivate},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(status,string), var(remove-date,string), var(modification-datetime,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(partner-login,string), var(partner-password,string), var(country-code,string), var(webapi-key,string),var(session-id,string)}),sdec(doPartnerLogin), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPartnerLogin},{haha}, {mycloud},in({var(partner-login,string), var(partner-password,string), var(country-code,string), var(webapi-key,string)}), out({var(session-id,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(session-id,string), var(webapi-key,string),var(result,string)}),sdec(doPartnerLogout), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPartnerLogout},{haha}, {mycloud},in({var(session-id,string), var(webapi-key,string)}), out({var(result,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion-id,string), var(session-id,string), var(webapi-key,string),var(photo-no,int)}),sdec(doPhotoDelete), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPhotoDelete},{haha}, {mycloud},in({var(insertion-id,string), var(session-id,string), var(webapi-key,string)}), out({var(photo-no,int)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion-id,string), var(photo,InsertionPhoto), var(session-id,string), var(webapi-key,string),var(photo-no,int), var(insertion-modification-datetime,string)}),sdec(doPhotoEdit), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPhotoEdit},{haha}, {mycloud},in({var(insertion-id,string), var(photo,InsertionPhoto), var(session-id,string), var(webapi-key,string)}), out({var(photo-no,int), var(insertion-modification-datetime,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(webapi-key,string),var(status,string), var(ad-password,string), var(error-list,ArrayOfFormErrors), var(insertion,Insertion)}),sdec(doPrivateInsertionAdd), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doPrivateInsertionAdd},{haha}, {mycloud},in({var(insertion,Insertion), var(webapi-key,string)}), out({var(status,string), var(ad-password,string), var(error-list,ArrayOfFormErrors), var(insertion,Insertion)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(insertion-number,string), var(name,string), var(email,string), var(phone,string), var(comment,string), var(captha-code,string), var(user-session-id,string),var(status,string), var(error-list,ArrayOfFormErrors)}),sdec(doSendContactForm), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doSendContactForm},{haha}, {mycloud},in({var(webapi-key,string), var(insertion-number,string), var(name,string), var(email,string), var(phone,string), var(comment,string), var(captha-code,string), var(user-session-id,string)}), out({var(status,string), var(error-list,ArrayOfFormErrors)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(advId,string), var(valuationLink,string), var(signature,string), var(webapi-key,string),var(status,string)}),sdec(doValuationResponse), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({doValuationResponse},{haha}, {mycloud},in({var(advId,string), var(valuationLink,string), var(signature,string), var(webapi-key,string)}), out({var(status,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(attribute-name,string), var(category,string), var(type,string), var(subtype1,string), var(subtype2,string), var(subtype3,string), var(webapi-key,string),var(dictionary-list,ArrayOfDictionaryItem)}),sdec(getAgroDictionary), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getAgroDictionary},{haha}, {mycloud},in({var(attribute-name,string), var(category,string), var(type,string), var(subtype1,string), var(subtype2,string), var(subtype3,string), var(webapi-key,string)}), out({var(dictionary-list,ArrayOfDictionaryItem)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(category-list,ArrayOfAllegroCategories)}),sdec(getAllegroCategories), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getAllegroCategories},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(category-list,ArrayOfAllegroCategories)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(currencies-list,ArrayOfCurrencies)}),sdec(getAllowedCurrencies), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getAllowedCurrencies},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(currencies-list,ArrayOfCurrencies)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(cobrand-id,int),var(news-list,ArrayOfArticleCategories)}),sdec(getArticleCategories), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getArticleCategories},{haha}, {mycloud},in({var(webapi-key,string), var(cobrand-id,int)}), out({var(news-list,ArrayOfArticleCategories)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(category-id,int), var(count,int), var(cobrand-id,int),var(article-list,ArrayOfArticles)}),sdec(getArticleList), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getArticleList},{haha}, {mycloud},in({var(webapi-key,string), var(category-id,int), var(count,int), var(cobrand-id,int)}), out({var(article-list,ArrayOfArticles)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(article-id,string), var(photo-no,int), var(photo-size,string), var(result-type,string), var(webapi-key,string),var(photo,ArticlePhoto)}),sdec(getArticlePhoto), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getArticlePhoto},{haha}, {mycloud},in({var(article-id,string), var(photo-no,int), var(photo-size,string), var(result-type,string), var(webapi-key,string)}), out({var(photo,ArticlePhoto)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(resource-type,string), var(resource-id,string), var(user-session-id,string),var(captcha-image,base64Binary)}),sdec(getCaptcha), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getCaptcha},{haha}, {mycloud},in({var(webapi-key,string), var(resource-type,string), var(resource-id,string), var(user-session-id,string)}), out({var(captcha-image,base64Binary)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(colours-list,ArrayOfColours)}),sdec(getColours), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getColours},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(colours-list,ArrayOfColours)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(attribute-name,string), var(category,string), var(webapi-key,string),var(dictionary-list,ArrayOfDictionaryItem)}),sdec(getConstructionDictionary), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getConstructionDictionary},{haha}, {mycloud},in({var(attribute-name,string), var(category,string), var(webapi-key,string)}), out({var(dictionary-list,ArrayOfDictionaryItem)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(country-list,ArrayOfCountries)}),sdec(getCountries), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getCountries},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(country-list,ArrayOfCountries)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(session-id,string), var(webapi-key,string), var(offset,int), var(limit,int),var(status,string), var(insertions-list,ArrayOfInsertions)}),sdec(getDealerInsertions), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getDealerInsertions},{haha}, {mycloud},in({var(type,string), var(session-id,string), var(webapi-key,string), var(offset,int), var(limit,int)}), out({var(status,string), var(insertions-list,ArrayOfInsertions)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(object-type,string),var(fuel-type-list,ArrayOfFuelTypes)}),sdec(getFuelTypes), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getFuelTypes},{haha}, {mycloud},in({var(webapi-key,string), var(object-type,string)}), out({var(fuel-type-list,ArrayOfFuelTypes)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(gear-box-type-list,ArrayOfGearBoxTypes)}),sdec(getGearBoxTypes), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getGearBoxTypes},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(gear-box-type-list,ArrayOfGearBoxTypes)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion,Insertion), var(session-id,string), var(webapi-key,string),var(insertion,Insertion)}),sdec(getInsertion), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getInsertion},{haha}, {mycloud},in({var(insertion,Insertion), var(session-id,string), var(webapi-key,string)}), out({var(insertion,Insertion)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion-id,string), var(photo-no,int), var(photo-size,string), var(result-type,string), var(webapi-key,string),var(photo,InsertionPhoto)}),sdec(getInsertionPhoto), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getInsertionPhoto},{haha}, {mycloud},in({var(insertion-id,string), var(photo-no,int), var(photo-size,string), var(result-type,string), var(webapi-key,string)}), out({var(photo,InsertionPhoto)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(search-query-id,long), var(start-pos,int), var(results-limit,int), var(webapi-key,string), var(only-promoted,string),var(results-list,ArrayOfInsertions)}),sdec(getInsertionSearchResults), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getInsertionSearchResults},{haha}, {mycloud},in({var(search-query-id,long), var(start-pos,int), var(results-limit,int), var(webapi-key,string), var(only-promoted,string)}), out({var(results-list,ArrayOfInsertions)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(insertion,Insertion)}),sdec(getMainPageInsertion), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getMainPageInsertion},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(insertion,Insertion)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(webapi-key,string), var(group,string),var(make-list,ArrayOfMakes)}),sdec(getMakes), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getMakes},{haha}, {mycloud},in({var(type,string), var(webapi-key,string), var(group,string)}), out({var(make-list,ArrayOfMakes)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(make-id,int), var(webapi-key,string), var(country-code,string), var(type,string),var(model-list,ArrayOfModels)}),sdec(getModels), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getModels},{haha}, {mycloud},in({var(make-id,int), var(webapi-key,string), var(country-code,string), var(type,string)}), out({var(model-list,ArrayOfModels)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(cobrand-id,int),var(news-list,ArrayOfNews)}),sdec(getNewsList), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getNewsList},{haha}, {mycloud},in({var(webapi-key,string), var(cobrand-id,int)}), out({var(news-list,ArrayOfNews)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(news-id,string), var(photo-no,int), var(webapi-key,string), var(photo-size,string), var(result-type,string),var(photo,NewsPhoto)}),sdec(getNewsPhoto), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getNewsPhoto},{haha}, {mycloud},in({var(news-id,string), var(photo-no,int), var(webapi-key,string), var(photo-size,string), var(result-type,string)}), out({var(photo,NewsPhoto)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(kind,string), var(webapi-key,string),var(part-categories-list,ArrayOfPartCategories)}),sdec(getPartCategories), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getPartCategories},{haha}, {mycloud},in({var(kind,string), var(webapi-key,string)}), out({var(part-categories-list,ArrayOfPartCategories)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(session-id,string), var(webapi-key,string), var(limit,int), var(offset,int),var(status,string), var(insertions-list,ArrayOfInsertions)}),sdec(getPartnerInsertions), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getPartnerInsertions},{haha}, {mycloud},in({var(type,string), var(session-id,string), var(webapi-key,string), var(limit,int), var(offset,int)}), out({var(status,string), var(insertions-list,ArrayOfInsertions)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(session-id,string), var(webapi-key,string),var(status,string), var(number,int)}),sdec(getPartnerInsertionsNumber), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getPartnerInsertionsNumber},{haha}, {mycloud},in({var(type,string), var(session-id,string), var(webapi-key,string)}), out({var(status,string), var(number,int)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(insertion-id,string), var(session-id,string), var(webapi-key,string),var(sms-code,string)}),sdec(getPrivateActivationCode), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getPrivateActivationCode},{haha}, {mycloud},in({var(insertion-id,string), var(session-id,string), var(webapi-key,string)}), out({var(sms-code,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(results-limit,int), var(webapi-key,string),var(results-list,ArrayOfInsertions)}),sdec(getPromotedInsertions), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getPromotedInsertions},{haha}, {mycloud},in({var(results-limit,int), var(webapi-key,string)}), out({var(results-list,ArrayOfInsertions)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(country-id,string), var(webapi-key,string),var(province-list,ArrayOfProvinces)}),sdec(getProvinces), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getProvinces},{haha}, {mycloud},in({var(country-id,string), var(webapi-key,string)}), out({var(province-list,ArrayOfProvinces)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(type,string), var(params,ArrayOfKeyValue), var(page,int), var(limit,int), var(sort,string),var(count,int), var(searchItems,ArrayOfSearchItems), var(status,string), var(errors,ArrayOfStrings)}),sdec(getSearchItems), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getSearchItems},{haha}, {mycloud},in({var(webapi-key,string), var(type,string), var(params,ArrayOfKeyValue), var(page,int), var(limit,int), var(sort,string)}), out({var(count,int), var(searchItems,ArrayOfSearchItems), var(status,string), var(errors,ArrayOfStrings)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(type,string),var(params,ArrayOfStrings)}),sdec(getSearchParams), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getSearchParams},{haha}, {mycloud},in({var(webapi-key,string), var(type,string)}), out({var(params,ArrayOfStrings)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string),var(webapi-version,float), var(vehicle-data-version,float), var(allegro-categories-version,float), var(models-version,int), var(motd-body,string), var(motd-link,string)}),sdec(getSystemInfo), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getSystemInfo},{haha}, {mycloud},in({var(webapi-key,string)}), out({var(webapi-version,float), var(vehicle-data-version,float), var(allegro-categories-version,float), var(models-version,int), var(motd-body,string), var(motd-link,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(string-size,int), var(webapi-key,string),var(return-string,string)}),sdec(getTestString), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getTestString},{haha}, {mycloud},in({var(string-size,int), var(webapi-key,string)}), out({var(return-string,string)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(webapi-key,string),var(transmission-list,ArrayOfTransmissionTypes)}),sdec(getTransmissionTypes), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getTransmissionTypes},{haha}, {mycloud},in({var(type,string), var(webapi-key,string)}), out({var(transmission-list,ArrayOfTransmissionTypes)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(webapi-key,string), var(user-type,string), var(user-id,string), var(limit,int), var(page,int), var(sort-by,string),var(results-list,ArrayOfInsertions), var(results-count,int)}),sdec(getUserInsertions), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getUserInsertions},{haha}, {mycloud},in({var(webapi-key,string), var(user-type,string), var(user-id,string), var(limit,int), var(page,int), var(sort-by,string)}), out({var(results-list,ArrayOfInsertions), var(results-count,int)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(webapi-key,string),var(category-list,ArrayOfVehicleCategories)}),sdec(getVehicleCategories), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getVehicleCategories},{haha}, {mycloud},in({var(type,string), var(webapi-key,string)}), out({var(category-list,ArrayOfVehicleCategories)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(webapi-key,string),var(vehicle-extras-list,ArrayOfVehicleExtras)}),sdec(getVehicleExtras), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getVehicleExtras},{haha}, {mycloud},in({var(type,string), var(webapi-key,string)}), out({var(vehicle-extras-list,ArrayOfVehicleExtras)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(type,string), var(webapi-key,string),var(vehicle-features-list,ArrayOfVehicleFeatures)}),sdec(getVehicleFeatures), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getVehicleFeatures},{haha}, {mycloud},in({var(type,string), var(webapi-key,string)}), out({var(vehicle-features-list,ArrayOfVehicleFeatures)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(category,string), var(webapi-key,string),var(kind-list,ArrayOfVehicleCategories)}),sdec(getVehicleKinds), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getVehicleKinds},{haha}, {mycloud},in({var(category,string), var(webapi-key,string)}), out({var(kind-list,ArrayOfVehicleCategories)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).
atomService(rdec({var(make-id,int), var(model-id,int), var(webapi-key,string), var(country-code,string), var(type,string),var(version-list,ArrayOfVersions)}),sdec(getVersions), sign(openservice,http://otomoto.wp.pl:80/webapi/server.php), funcR({getVersions},{haha}, {mycloud},in({var(make-id,int), var(model-id,int), var(webapi-key,string), var(country-code,string), var(type,string)}), out({var(version-list,ArrayOfVersions)})), nonFuncR("327.13","13.00","5.10","67.00","0.00",""0", "0")).

atomService(rdec({var(params,string),var(result,string)}),sdec(ServiceRequest), sign(openservice,http://th.sbuypayment.com/webservices/Pay.php), funcR({ServiceRequest},{haha}, {mycloud},in({var(params,string)}), out({var(result,string)})), nonFuncR("413.00","83.00","17.80","78.00","0.00",""0", "0")).

atomService(rdec({var(request,Request),var(return,ResponSales)}),sdec(selectSales), sign(openservice,http://www.jdesign.ru/server.php), funcR({selectSales},{haha}, {mycloud},in({var(request,Request)}), out({var(return,ResponSales)})), nonFuncR("503.67","63.00","4.90","73.00","0.00",""0", "0")).
atomService(rdec({var(request,updateReguest),var(return,updateResponse)}),sdec(updateSales), sign(openservice,http://www.jdesign.ru/server.php), funcR({updateSales},{haha}, {mycloud},in({var(request,updateReguest)}), out({var(return,updateResponse)})), nonFuncR("503.67","63.00","4.90","73.00","0.00",""0", "0")).
atomService(rdec({var(request,insertReguest),var(return,insertResponse)}),sdec(insertSales), sign(openservice,http://www.jdesign.ru/server.php), funcR({insertSales},{haha}, {mycloud},in({var(request,insertReguest)}), out({var(return,insertResponse)})), nonFuncR("503.67","63.00","4.90","73.00","0.00",""0", "0")).
